# Site settings
title: Matthew's Projects and Stuff
name: Matthew Crouch
email: your-email@domain.com
baseurl: ""
url: "http://matt-crouch.com"
twitter_username: matt_crouch
github_username:  macrouch

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
